import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className=" grid grid-cols-4 bg-[#F4F4FA] h-[100vh] items-center px-10 gap-4 ">
          <div className="bg-white h-[90%] rounded-[30px] p-4">
              <SideBar/>
          </div>
          <div className=" col-span-3 bg-white h-[90%] rounded-[30px] p-4">
                {children}

          </div>
      </body>
    </html>
  );
}
